server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: m0veFast!

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl